/* eslint-disable */
/* Auto-generated by scripts/generate-phone-countries.mjs — do not edit by hand. */

export const PHONE_COUNTRIES = [
  {
    "region": "HK",
    "dialCode": "852",
    "englishName": "Hong Kong SAR China"
  },
  {
    "region": "CN",
    "dialCode": "86",
    "englishName": "China"
  },
  {
    "region": "MO",
    "dialCode": "853",
    "englishName": "Macao SAR China"
  },
  {
    "region": "TW",
    "dialCode": "886",
    "englishName": "Taiwan"
  },
  {
    "region": "SG",
    "dialCode": "65",
    "englishName": "Singapore"
  },
  {
    "region": "MY",
    "dialCode": "60",
    "englishName": "Malaysia"
  },
  {
    "region": "TH",
    "dialCode": "66",
    "englishName": "Thailand"
  },
  {
    "region": "VN",
    "dialCode": "84",
    "englishName": "Vietnam"
  },
  {
    "region": "ID",
    "dialCode": "62",
    "englishName": "Indonesia"
  },
  {
    "region": "PH",
    "dialCode": "63",
    "englishName": "Philippines"
  },
  {
    "region": "JP",
    "dialCode": "81",
    "englishName": "Japan"
  },
  {
    "region": "KR",
    "dialCode": "82",
    "englishName": "South Korea"
  },
  {
    "region": "IN",
    "dialCode": "91",
    "englishName": "India"
  },
  {
    "region": "AU",
    "dialCode": "61",
    "englishName": "Australia"
  },
  {
    "region": "NZ",
    "dialCode": "64",
    "englishName": "New Zealand"
  },
  {
    "region": "GB",
    "dialCode": "44",
    "englishName": "United Kingdom"
  },
  {
    "region": "US",
    "dialCode": "1",
    "englishName": "United States"
  },
  {
    "region": "CA",
    "dialCode": "1",
    "englishName": "Canada"
  },
  {
    "region": "DE",
    "dialCode": "49",
    "englishName": "Germany"
  },
  {
    "region": "FR",
    "dialCode": "33",
    "englishName": "France"
  },
  {
    "region": "IT",
    "dialCode": "39",
    "englishName": "Italy"
  },
  {
    "region": "ES",
    "dialCode": "34",
    "englishName": "Spain"
  },
  {
    "region": "NL",
    "dialCode": "31",
    "englishName": "Netherlands"
  },
  {
    "region": "BE",
    "dialCode": "32",
    "englishName": "Belgium"
  },
  {
    "region": "CH",
    "dialCode": "41",
    "englishName": "Switzerland"
  },
  {
    "region": "AE",
    "dialCode": "971",
    "englishName": "United Arab Emirates"
  },
  {
    "region": "SA",
    "dialCode": "966",
    "englishName": "Saudi Arabia"
  },
  {
    "region": "ZA",
    "dialCode": "27",
    "englishName": "South Africa"
  },
  {
    "region": "PT",
    "dialCode": "351",
    "englishName": "Portugal"
  },
  {
    "region": "IE",
    "dialCode": "353",
    "englishName": "Ireland"
  },
  {
    "region": "AC",
    "dialCode": "247",
    "englishName": "Ascension Island"
  },
  {
    "region": "AD",
    "dialCode": "376",
    "englishName": "Andorra"
  },
  {
    "region": "AF",
    "dialCode": "93",
    "englishName": "Afghanistan"
  },
  {
    "region": "AG",
    "dialCode": "1",
    "englishName": "Antigua & Barbuda"
  },
  {
    "region": "AI",
    "dialCode": "1",
    "englishName": "Anguilla"
  },
  {
    "region": "AL",
    "dialCode": "355",
    "englishName": "Albania"
  },
  {
    "region": "AM",
    "dialCode": "374",
    "englishName": "Armenia"
  },
  {
    "region": "AO",
    "dialCode": "244",
    "englishName": "Angola"
  },
  {
    "region": "AR",
    "dialCode": "54",
    "englishName": "Argentina"
  },
  {
    "region": "AS",
    "dialCode": "1",
    "englishName": "American Samoa"
  },
  {
    "region": "AT",
    "dialCode": "43",
    "englishName": "Austria"
  },
  {
    "region": "AW",
    "dialCode": "297",
    "englishName": "Aruba"
  },
  {
    "region": "AX",
    "dialCode": "358",
    "englishName": "Åland Islands"
  },
  {
    "region": "AZ",
    "dialCode": "994",
    "englishName": "Azerbaijan"
  },
  {
    "region": "BA",
    "dialCode": "387",
    "englishName": "Bosnia & Herzegovina"
  },
  {
    "region": "BB",
    "dialCode": "1",
    "englishName": "Barbados"
  },
  {
    "region": "BD",
    "dialCode": "880",
    "englishName": "Bangladesh"
  },
  {
    "region": "BF",
    "dialCode": "226",
    "englishName": "Burkina Faso"
  },
  {
    "region": "BG",
    "dialCode": "359",
    "englishName": "Bulgaria"
  },
  {
    "region": "BH",
    "dialCode": "973",
    "englishName": "Bahrain"
  },
  {
    "region": "BI",
    "dialCode": "257",
    "englishName": "Burundi"
  },
  {
    "region": "BJ",
    "dialCode": "229",
    "englishName": "Benin"
  },
  {
    "region": "BL",
    "dialCode": "590",
    "englishName": "St. Barthélemy"
  },
  {
    "region": "BM",
    "dialCode": "1",
    "englishName": "Bermuda"
  },
  {
    "region": "BN",
    "dialCode": "673",
    "englishName": "Brunei"
  },
  {
    "region": "BO",
    "dialCode": "591",
    "englishName": "Bolivia"
  },
  {
    "region": "BQ",
    "dialCode": "599",
    "englishName": "Caribbean Netherlands"
  },
  {
    "region": "BR",
    "dialCode": "55",
    "englishName": "Brazil"
  },
  {
    "region": "BS",
    "dialCode": "1",
    "englishName": "Bahamas"
  },
  {
    "region": "BT",
    "dialCode": "975",
    "englishName": "Bhutan"
  },
  {
    "region": "BW",
    "dialCode": "267",
    "englishName": "Botswana"
  },
  {
    "region": "BY",
    "dialCode": "375",
    "englishName": "Belarus"
  },
  {
    "region": "BZ",
    "dialCode": "501",
    "englishName": "Belize"
  },
  {
    "region": "CC",
    "dialCode": "61",
    "englishName": "Cocos (Keeling) Islands"
  },
  {
    "region": "CD",
    "dialCode": "243",
    "englishName": "Congo - Kinshasa"
  },
  {
    "region": "CF",
    "dialCode": "236",
    "englishName": "Central African Republic"
  },
  {
    "region": "CG",
    "dialCode": "242",
    "englishName": "Congo - Brazzaville"
  },
  {
    "region": "CI",
    "dialCode": "225",
    "englishName": "Côte d’Ivoire"
  },
  {
    "region": "CK",
    "dialCode": "682",
    "englishName": "Cook Islands"
  },
  {
    "region": "CL",
    "dialCode": "56",
    "englishName": "Chile"
  },
  {
    "region": "CM",
    "dialCode": "237",
    "englishName": "Cameroon"
  },
  {
    "region": "CO",
    "dialCode": "57",
    "englishName": "Colombia"
  },
  {
    "region": "CR",
    "dialCode": "506",
    "englishName": "Costa Rica"
  },
  {
    "region": "CU",
    "dialCode": "53",
    "englishName": "Cuba"
  },
  {
    "region": "CV",
    "dialCode": "238",
    "englishName": "Cape Verde"
  },
  {
    "region": "CW",
    "dialCode": "599",
    "englishName": "Curaçao"
  },
  {
    "region": "CX",
    "dialCode": "61",
    "englishName": "Christmas Island"
  },
  {
    "region": "CY",
    "dialCode": "357",
    "englishName": "Cyprus"
  },
  {
    "region": "CZ",
    "dialCode": "420",
    "englishName": "Czechia"
  },
  {
    "region": "DJ",
    "dialCode": "253",
    "englishName": "Djibouti"
  },
  {
    "region": "DK",
    "dialCode": "45",
    "englishName": "Denmark"
  },
  {
    "region": "DM",
    "dialCode": "1",
    "englishName": "Dominica"
  },
  {
    "region": "DO",
    "dialCode": "1",
    "englishName": "Dominican Republic"
  },
  {
    "region": "DZ",
    "dialCode": "213",
    "englishName": "Algeria"
  },
  {
    "region": "EC",
    "dialCode": "593",
    "englishName": "Ecuador"
  },
  {
    "region": "EE",
    "dialCode": "372",
    "englishName": "Estonia"
  },
  {
    "region": "EG",
    "dialCode": "20",
    "englishName": "Egypt"
  },
  {
    "region": "EH",
    "dialCode": "212",
    "englishName": "Western Sahara"
  },
  {
    "region": "ER",
    "dialCode": "291",
    "englishName": "Eritrea"
  },
  {
    "region": "ET",
    "dialCode": "251",
    "englishName": "Ethiopia"
  },
  {
    "region": "FI",
    "dialCode": "358",
    "englishName": "Finland"
  },
  {
    "region": "FJ",
    "dialCode": "679",
    "englishName": "Fiji"
  },
  {
    "region": "FK",
    "dialCode": "500",
    "englishName": "Falkland Islands"
  },
  {
    "region": "FM",
    "dialCode": "691",
    "englishName": "Micronesia"
  },
  {
    "region": "FO",
    "dialCode": "298",
    "englishName": "Faroe Islands"
  },
  {
    "region": "GA",
    "dialCode": "241",
    "englishName": "Gabon"
  },
  {
    "region": "GD",
    "dialCode": "1",
    "englishName": "Grenada"
  },
  {
    "region": "GE",
    "dialCode": "995",
    "englishName": "Georgia"
  },
  {
    "region": "GF",
    "dialCode": "594",
    "englishName": "French Guiana"
  },
  {
    "region": "GG",
    "dialCode": "44",
    "englishName": "Guernsey"
  },
  {
    "region": "GH",
    "dialCode": "233",
    "englishName": "Ghana"
  },
  {
    "region": "GI",
    "dialCode": "350",
    "englishName": "Gibraltar"
  },
  {
    "region": "GL",
    "dialCode": "299",
    "englishName": "Greenland"
  },
  {
    "region": "GM",
    "dialCode": "220",
    "englishName": "Gambia"
  },
  {
    "region": "GN",
    "dialCode": "224",
    "englishName": "Guinea"
  },
  {
    "region": "GP",
    "dialCode": "590",
    "englishName": "Guadeloupe"
  },
  {
    "region": "GQ",
    "dialCode": "240",
    "englishName": "Equatorial Guinea"
  },
  {
    "region": "GR",
    "dialCode": "30",
    "englishName": "Greece"
  },
  {
    "region": "GT",
    "dialCode": "502",
    "englishName": "Guatemala"
  },
  {
    "region": "GU",
    "dialCode": "1",
    "englishName": "Guam"
  },
  {
    "region": "GW",
    "dialCode": "245",
    "englishName": "Guinea-Bissau"
  },
  {
    "region": "GY",
    "dialCode": "592",
    "englishName": "Guyana"
  },
  {
    "region": "HN",
    "dialCode": "504",
    "englishName": "Honduras"
  },
  {
    "region": "HR",
    "dialCode": "385",
    "englishName": "Croatia"
  },
  {
    "region": "HT",
    "dialCode": "509",
    "englishName": "Haiti"
  },
  {
    "region": "HU",
    "dialCode": "36",
    "englishName": "Hungary"
  },
  {
    "region": "IL",
    "dialCode": "972",
    "englishName": "Israel"
  },
  {
    "region": "IM",
    "dialCode": "44",
    "englishName": "Isle of Man"
  },
  {
    "region": "IO",
    "dialCode": "246",
    "englishName": "British Indian Ocean Territory"
  },
  {
    "region": "IQ",
    "dialCode": "964",
    "englishName": "Iraq"
  },
  {
    "region": "IR",
    "dialCode": "98",
    "englishName": "Iran"
  },
  {
    "region": "IS",
    "dialCode": "354",
    "englishName": "Iceland"
  },
  {
    "region": "JE",
    "dialCode": "44",
    "englishName": "Jersey"
  },
  {
    "region": "JM",
    "dialCode": "1",
    "englishName": "Jamaica"
  },
  {
    "region": "JO",
    "dialCode": "962",
    "englishName": "Jordan"
  },
  {
    "region": "KE",
    "dialCode": "254",
    "englishName": "Kenya"
  },
  {
    "region": "KG",
    "dialCode": "996",
    "englishName": "Kyrgyzstan"
  },
  {
    "region": "KH",
    "dialCode": "855",
    "englishName": "Cambodia"
  },
  {
    "region": "KI",
    "dialCode": "686",
    "englishName": "Kiribati"
  },
  {
    "region": "KM",
    "dialCode": "269",
    "englishName": "Comoros"
  },
  {
    "region": "KN",
    "dialCode": "1",
    "englishName": "St. Kitts & Nevis"
  },
  {
    "region": "KP",
    "dialCode": "850",
    "englishName": "North Korea"
  },
  {
    "region": "KW",
    "dialCode": "965",
    "englishName": "Kuwait"
  },
  {
    "region": "KY",
    "dialCode": "1",
    "englishName": "Cayman Islands"
  },
  {
    "region": "KZ",
    "dialCode": "7",
    "englishName": "Kazakhstan"
  },
  {
    "region": "LA",
    "dialCode": "856",
    "englishName": "Laos"
  },
  {
    "region": "LB",
    "dialCode": "961",
    "englishName": "Lebanon"
  },
  {
    "region": "LC",
    "dialCode": "1",
    "englishName": "St. Lucia"
  },
  {
    "region": "LI",
    "dialCode": "423",
    "englishName": "Liechtenstein"
  },
  {
    "region": "LK",
    "dialCode": "94",
    "englishName": "Sri Lanka"
  },
  {
    "region": "LR",
    "dialCode": "231",
    "englishName": "Liberia"
  },
  {
    "region": "LS",
    "dialCode": "266",
    "englishName": "Lesotho"
  },
  {
    "region": "LT",
    "dialCode": "370",
    "englishName": "Lithuania"
  },
  {
    "region": "LU",
    "dialCode": "352",
    "englishName": "Luxembourg"
  },
  {
    "region": "LV",
    "dialCode": "371",
    "englishName": "Latvia"
  },
  {
    "region": "LY",
    "dialCode": "218",
    "englishName": "Libya"
  },
  {
    "region": "MA",
    "dialCode": "212",
    "englishName": "Morocco"
  },
  {
    "region": "MC",
    "dialCode": "377",
    "englishName": "Monaco"
  },
  {
    "region": "MD",
    "dialCode": "373",
    "englishName": "Moldova"
  },
  {
    "region": "ME",
    "dialCode": "382",
    "englishName": "Montenegro"
  },
  {
    "region": "MF",
    "dialCode": "590",
    "englishName": "St. Martin"
  },
  {
    "region": "MG",
    "dialCode": "261",
    "englishName": "Madagascar"
  },
  {
    "region": "MH",
    "dialCode": "692",
    "englishName": "Marshall Islands"
  },
  {
    "region": "MK",
    "dialCode": "389",
    "englishName": "North Macedonia"
  },
  {
    "region": "ML",
    "dialCode": "223",
    "englishName": "Mali"
  },
  {
    "region": "MM",
    "dialCode": "95",
    "englishName": "Myanmar (Burma)"
  },
  {
    "region": "MN",
    "dialCode": "976",
    "englishName": "Mongolia"
  },
  {
    "region": "MP",
    "dialCode": "1",
    "englishName": "Northern Mariana Islands"
  },
  {
    "region": "MQ",
    "dialCode": "596",
    "englishName": "Martinique"
  },
  {
    "region": "MR",
    "dialCode": "222",
    "englishName": "Mauritania"
  },
  {
    "region": "MS",
    "dialCode": "1",
    "englishName": "Montserrat"
  },
  {
    "region": "MT",
    "dialCode": "356",
    "englishName": "Malta"
  },
  {
    "region": "MU",
    "dialCode": "230",
    "englishName": "Mauritius"
  },
  {
    "region": "MV",
    "dialCode": "960",
    "englishName": "Maldives"
  },
  {
    "region": "MW",
    "dialCode": "265",
    "englishName": "Malawi"
  },
  {
    "region": "MX",
    "dialCode": "52",
    "englishName": "Mexico"
  },
  {
    "region": "MZ",
    "dialCode": "258",
    "englishName": "Mozambique"
  },
  {
    "region": "NA",
    "dialCode": "264",
    "englishName": "Namibia"
  },
  {
    "region": "NC",
    "dialCode": "687",
    "englishName": "New Caledonia"
  },
  {
    "region": "NE",
    "dialCode": "227",
    "englishName": "Niger"
  },
  {
    "region": "NF",
    "dialCode": "672",
    "englishName": "Norfolk Island"
  },
  {
    "region": "NG",
    "dialCode": "234",
    "englishName": "Nigeria"
  },
  {
    "region": "NI",
    "dialCode": "505",
    "englishName": "Nicaragua"
  },
  {
    "region": "NO",
    "dialCode": "47",
    "englishName": "Norway"
  },
  {
    "region": "NP",
    "dialCode": "977",
    "englishName": "Nepal"
  },
  {
    "region": "NR",
    "dialCode": "674",
    "englishName": "Nauru"
  },
  {
    "region": "NU",
    "dialCode": "683",
    "englishName": "Niue"
  },
  {
    "region": "OM",
    "dialCode": "968",
    "englishName": "Oman"
  },
  {
    "region": "PA",
    "dialCode": "507",
    "englishName": "Panama"
  },
  {
    "region": "PE",
    "dialCode": "51",
    "englishName": "Peru"
  },
  {
    "region": "PF",
    "dialCode": "689",
    "englishName": "French Polynesia"
  },
  {
    "region": "PG",
    "dialCode": "675",
    "englishName": "Papua New Guinea"
  },
  {
    "region": "PK",
    "dialCode": "92",
    "englishName": "Pakistan"
  },
  {
    "region": "PL",
    "dialCode": "48",
    "englishName": "Poland"
  },
  {
    "region": "PM",
    "dialCode": "508",
    "englishName": "St. Pierre & Miquelon"
  },
  {
    "region": "PR",
    "dialCode": "1",
    "englishName": "Puerto Rico"
  },
  {
    "region": "PS",
    "dialCode": "970",
    "englishName": "Palestinian Territories"
  },
  {
    "region": "PW",
    "dialCode": "680",
    "englishName": "Palau"
  },
  {
    "region": "PY",
    "dialCode": "595",
    "englishName": "Paraguay"
  },
  {
    "region": "QA",
    "dialCode": "974",
    "englishName": "Qatar"
  },
  {
    "region": "RE",
    "dialCode": "262",
    "englishName": "Réunion"
  },
  {
    "region": "RO",
    "dialCode": "40",
    "englishName": "Romania"
  },
  {
    "region": "RS",
    "dialCode": "381",
    "englishName": "Serbia"
  },
  {
    "region": "RU",
    "dialCode": "7",
    "englishName": "Russia"
  },
  {
    "region": "RW",
    "dialCode": "250",
    "englishName": "Rwanda"
  },
  {
    "region": "SB",
    "dialCode": "677",
    "englishName": "Solomon Islands"
  },
  {
    "region": "SC",
    "dialCode": "248",
    "englishName": "Seychelles"
  },
  {
    "region": "SD",
    "dialCode": "249",
    "englishName": "Sudan"
  },
  {
    "region": "SE",
    "dialCode": "46",
    "englishName": "Sweden"
  },
  {
    "region": "SH",
    "dialCode": "290",
    "englishName": "St. Helena"
  },
  {
    "region": "SI",
    "dialCode": "386",
    "englishName": "Slovenia"
  },
  {
    "region": "SJ",
    "dialCode": "47",
    "englishName": "Svalbard & Jan Mayen"
  },
  {
    "region": "SK",
    "dialCode": "421",
    "englishName": "Slovakia"
  },
  {
    "region": "SL",
    "dialCode": "232",
    "englishName": "Sierra Leone"
  },
  {
    "region": "SM",
    "dialCode": "378",
    "englishName": "San Marino"
  },
  {
    "region": "SN",
    "dialCode": "221",
    "englishName": "Senegal"
  },
  {
    "region": "SO",
    "dialCode": "252",
    "englishName": "Somalia"
  },
  {
    "region": "SR",
    "dialCode": "597",
    "englishName": "Suriname"
  },
  {
    "region": "SS",
    "dialCode": "211",
    "englishName": "South Sudan"
  },
  {
    "region": "ST",
    "dialCode": "239",
    "englishName": "São Tomé & Príncipe"
  },
  {
    "region": "SV",
    "dialCode": "503",
    "englishName": "El Salvador"
  },
  {
    "region": "SX",
    "dialCode": "1",
    "englishName": "Sint Maarten"
  },
  {
    "region": "SY",
    "dialCode": "963",
    "englishName": "Syria"
  },
  {
    "region": "SZ",
    "dialCode": "268",
    "englishName": "Eswatini"
  },
  {
    "region": "TA",
    "dialCode": "290",
    "englishName": "Tristan da Cunha"
  },
  {
    "region": "TC",
    "dialCode": "1",
    "englishName": "Turks & Caicos Islands"
  },
  {
    "region": "TD",
    "dialCode": "235",
    "englishName": "Chad"
  },
  {
    "region": "TG",
    "dialCode": "228",
    "englishName": "Togo"
  },
  {
    "region": "TJ",
    "dialCode": "992",
    "englishName": "Tajikistan"
  },
  {
    "region": "TK",
    "dialCode": "690",
    "englishName": "Tokelau"
  },
  {
    "region": "TL",
    "dialCode": "670",
    "englishName": "Timor-Leste"
  },
  {
    "region": "TM",
    "dialCode": "993",
    "englishName": "Turkmenistan"
  },
  {
    "region": "TN",
    "dialCode": "216",
    "englishName": "Tunisia"
  },
  {
    "region": "TO",
    "dialCode": "676",
    "englishName": "Tonga"
  },
  {
    "region": "TR",
    "dialCode": "90",
    "englishName": "Türkiye"
  },
  {
    "region": "TT",
    "dialCode": "1",
    "englishName": "Trinidad & Tobago"
  },
  {
    "region": "TV",
    "dialCode": "688",
    "englishName": "Tuvalu"
  },
  {
    "region": "TZ",
    "dialCode": "255",
    "englishName": "Tanzania"
  },
  {
    "region": "UA",
    "dialCode": "380",
    "englishName": "Ukraine"
  },
  {
    "region": "UG",
    "dialCode": "256",
    "englishName": "Uganda"
  },
  {
    "region": "UY",
    "dialCode": "598",
    "englishName": "Uruguay"
  },
  {
    "region": "UZ",
    "dialCode": "998",
    "englishName": "Uzbekistan"
  },
  {
    "region": "VA",
    "dialCode": "39",
    "englishName": "Vatican City"
  },
  {
    "region": "VC",
    "dialCode": "1",
    "englishName": "St. Vincent & Grenadines"
  },
  {
    "region": "VE",
    "dialCode": "58",
    "englishName": "Venezuela"
  },
  {
    "region": "VG",
    "dialCode": "1",
    "englishName": "British Virgin Islands"
  },
  {
    "region": "VI",
    "dialCode": "1",
    "englishName": "U.S. Virgin Islands"
  },
  {
    "region": "VU",
    "dialCode": "678",
    "englishName": "Vanuatu"
  },
  {
    "region": "WF",
    "dialCode": "681",
    "englishName": "Wallis & Futuna"
  },
  {
    "region": "WS",
    "dialCode": "685",
    "englishName": "Samoa"
  },
  {
    "region": "XK",
    "dialCode": "383",
    "englishName": "Kosovo"
  },
  {
    "region": "YE",
    "dialCode": "967",
    "englishName": "Yemen"
  },
  {
    "region": "YT",
    "dialCode": "262",
    "englishName": "Mayotte"
  },
  {
    "region": "ZM",
    "dialCode": "260",
    "englishName": "Zambia"
  },
  {
    "region": "ZW",
    "dialCode": "263",
    "englishName": "Zimbabwe"
  }
] as const;

export type PhoneCountryRow = (typeof PHONE_COUNTRIES)[number];
