openapi: 3.0.3
info:
  title: Search API
  version: 0.2.0
  description: |
    Route inventory for search/public routes in the current backend stack.

    At present, `backend/infrastructure/lib/api-stack.ts` does not wire any
    search/public booking routes from this spec into API Gateway.

    Notes:
    - Public reservation handler code exists inside
      `backend/src/app/api/public_reservations.py` and is dispatched by
      `backend/src/app/api/admin.py` when the request path matches
      `/v1/reservations`.
    - These handler-level capabilities are not currently exposed through
      API Gateway route resources in the CDK stack.

servers:
  - url: https://api.evolvesprouts.com
    description: Production custom domain (when configured)
  - url: https://{restApiId}.execute-api.{region}.amazonaws.com/prod
    description: API Gateway invoke URL
    variables:
      restApiId:
        default: example
      region:
        default: ap-southeast-1

paths: {}
